
#ifndef _FDSOUND_ENUMS_H_
#define _FDSOUND_ENUMS_H_

// Music enumerations
enum {
  FD_MENU_MUSIC,

  FD_NUM_MUSIC
};

// SFX Enumerations
enum {
  FD_SFX_CROWD_CARD_APPROVAL,
  FD_SFX_CROWD_CARD_DONTAGREE,
  FD_SFX_CROWD_CHANT1_LOOP_837,
  FD_SFX_CROWD_CHANT2_LOOP_7015,
  FD_SFX_CROWD_CHANT3_LOOP_1325,
  FD_SFX_CROWD_CLOSESHOT1,
  FD_SFX_CROWD_CLOSESHOT2,
  FD_SFX_CROWD_DISAPPOINTED_REACTION,
  FD_SFX_CROWD_EXCITED_LOOP_351,
  FD_SFX_CROWD_GENERAL1_LOOP_3029,
  FD_SFX_CROWD_GENERAL1_LOOP_886,
  FD_SFX_CROWD_GOAL1,
  FD_SFX_CROWD_GOAL2,
  FD_SFX_CROWD_HAPPY_LOOP_15436,
  FD_SFX_CROWD_JUBILANT_LOOP_3554,
  FD_SFX_CROWD_PREMATCH_LOOP_3003,
  FD_SFX_CROWD_UPSET_LOOP_17490,
  FD_SFX_MATCH_PAUSE,
  FD_SFX_MATCH_RESUME,
  FD_SFX_REF_WHISTLE,
  FD_SFX_REF_WHISTLE_FULLTIME,
  FD_SFX_REF_WHISTLE_HALFTIME,
  FD_SFX_UI_ADVANCE_TIME,
  FD_SFX_UI_BACK_BUTTON,
  FD_SFX_UI_CLICK,
  FD_SFX_UI_DISABLE,
  FD_SFX_UI_KERCHING,
  FD_SFX_UI_KEYBOARD_BACKSPACE,
  FD_SFX_UI_KEYBOARD_CLICK,
  FD_SFX_UI_SCROLL,
  FD_SFX_UI_SCROLL_NEGATIVE,
  FD_SFX_UI_SIDE_BUTTON,
  FD_SFX_VIDIPRINTER,

  FD_NUM_SFX
};

#endif
