<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: PocketPCFM - Win32 (WCE SH3) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating command line "rc.exe /l 0x409 /fo"e:\FootballDirector\PocketPC\PocketPCFM.res" /d UNDER_CE=400 /d _WIN32_WCE=400 /d "UNICODE" /d "_UNICODE" /d "DEBUG" /d "WCE_PLATFORM_STANDARDSDK" /d "SHx" /d "SH3" /d "_SH3_" /d "_AFXDLL" /r "D:\PROJECTS\POCKETPCFM\PocketPCFM.rc"" 
Creating temporary file "e:\temp\RSPC995.tmp" with contents
[
/nologo /W3 /Zi /Od /D "DEBUG" /D "SHx" /D "SH3" /D "_SH3_" /D UNDER_CE=400 /D _WIN32_WCE=400 /D "WCE_PLATFORM_STANDARDSDK" /D "UNICODE" /D "_UNICODE" /D "_AFXDLL" /Fp"e:\FootballDirector\PocketPC\PocketPCFM.pch" /Yu"stdafx.h" /Fo"e:\FootballDirector\PocketPC\\" /Fd"e:\FootballDirector\PocketPC\\" /MC /c 
"D:\PROJECTS\Applications\FootballDirector\ClubListBox.cpp"
"D:\PROJECTS\Applications\FootballDirector\DivisionListBox.CPP"
"D:\PROJECTS\POCKETPCFM\FootballDirectorDoc.cpp"
"D:\PROJECTS\POCKETPCFM\FootballDirectorView.cpp"
"D:\PROJECTS\POCKETPCFM\MainFrm.cpp"
"D:\PROJECTS\Applications\FootballDirector\MainMenu.cpp"
"D:\PROJECTS\Applications\FootballDirector\PopupPlayerMenu.cpp"
"D:\PROJECTS\POCKETPCFM\SoundManager.cpp"
"D:\PROJECTS\Applications\FootballDirector\TheApp.cpp"
"D:\PROJECTS\Sports\Soccer\MatchActionItem.cpp"
"D:\PROJECTS\Sports\Soccer\MatchCommentary.cpp"
"D:\PROJECTS\Sports\Soccer\MatchEvent.cpp"
"D:\PROJECTS\Sports\Soccer\MatchEventsStats.cpp"
"D:\PROJECTS\Sports\Soccer\MatchHandler.cpp"
"D:\PROJECTS\Sports\Soccer\MatchInfo.cpp"
"D:\PROJECTS\Sports\Soccer\MatchPlay.cpp"
"D:\PROJECTS\Sports\Soccer\MatchSubs.cpp"
"D:\PROJECTS\Sports\Soccer\MatchTeamSkills.cpp"
"D:\PROJECTS\Sports\Soccer\MatchTime.cpp"
"D:\PROJECTS\Sports\Soccer\MatchVars.cpp"
"D:\PROJECTS\Sports\Soccer\MatchVarsData.cpp"
"D:\PROJECTS\Sports\Soccer\PenaltyShootOut.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerBallPitchLocation.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerMatchPlayer.cpp"
"D:\PROJECTS\Sports\Soccer\Chairman.cpp"
"D:\PROJECTS\Sports\Soccer\Club.cpp"
"D:\PROJECTS\Sports\Soccer\ClubFriendlies.cpp"
"D:\PROJECTS\Sports\Soccer\ClubHistory.cpp"
"D:\PROJECTS\Sports\Soccer\ClubList.cpp"
"D:\PROJECTS\Sports\Soccer\ClubMatchDetails.cpp"
"D:\PROJECTS\Sports\Soccer\ClubSeasonStats.cpp"
"D:\PROJECTS\Sports\Soccer\ClubTransferOffer.cpp"
"D:\PROJECTS\Sports\Soccer\FansReaction.cpp"
"D:\PROJECTS\Sports\Soccer\SeasonLeaguePosition.cpp"
"D:\PROJECTS\Sports\Soccer\Injury.cpp"
"D:\PROJECTS\Sports\Soccer\InjuryType.cpp"
"D:\PROJECTS\Sports\Soccer\Player.cpp"
"D:\PROJECTS\Sports\Soccer\PlayerContract.cpp"
"D:\PROJECTS\Sports\Soccer\PlayerDiscipline.cpp"
"D:\PROJECTS\Sports\Soccer\PlayerLoan.cpp"
"D:\PROJECTS\Sports\Soccer\PlayerRating.cpp"
"D:\PROJECTS\Sports\Soccer\PlayerSquad.cpp"
"D:\PROJECTS\Sports\Soccer\PlayerTransferStatus.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerPlayer.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerPlayerCareer.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerPlayerCareerPath.cpp"
"D:\PROJECTS\Sports\Soccer\BaseCompetition.cpp"
"D:\PROJECTS\Sports\Soccer\CharityShield.cpp"
"D:\PROJECTS\Sports\Soccer\Competition.cpp"
"D:\PROJECTS\Sports\Soccer\Cup.CPP"
"D:\PROJECTS\Sports\Soccer\CupDisplayEvent.cpp"
"D:\PROJECTS\Sports\Soccer\CupRound.CPP"
"D:\PROJECTS\Sports\Soccer\CupTiedPlayer.cpp"
"D:\PROJECTS\Sports\Soccer\Division.cpp"
"D:\PROJECTS\Sports\Soccer\Playoff.cpp"
"D:\PROJECTS\Sports\Soccer\Accounts.cpp"
"D:\PROJECTS\Sports\Soccer\Aggression.cpp"
"D:\PROJECTS\Sports\Soccer\AvailableSubstitutes.cpp"
"D:\PROJECTS\Sports\Soccer\BasicEmployee.cpp"
"D:\PROJECTS\Sports\Soccer\ContractClause.cpp"
"D:\PROJECTS\Sports\Soccer\Country.cpp"
"D:\PROJECTS\Sports\Soccer\CupWinnersInfo.cpp"
"D:\PROJECTS\Sports\Soccer\Currency.cpp"
"D:\PROJECTS\Sports\Soccer\CurrentForm.cpp"
"D:\PROJECTS\Sports\Soccer\DivisionStrength.cpp"
"D:\PROJECTS\Sports\Soccer\Employee.cpp"
"D:\PROJECTS\Sports\Soccer\Federation.cpp"
"D:\PROJECTS\Sports\Soccer\FinancialLoan.cpp"
"D:\PROJECTS\Sports\Soccer\Fixture.cpp"
"D:\PROJECTS\Sports\Soccer\FixtureController.cpp"
"D:\PROJECTS\Sports\Soccer\HumanManager.cpp"
"D:\PROJECTS\Sports\Soccer\LeadingDisciplinaryPoints.cpp"
"D:\PROJECTS\Sports\Soccer\LeadingGoalscorer.cpp"
"D:\PROJECTS\Sports\Soccer\Manager.cpp"
"D:\PROJECTS\Sports\Soccer\ManagerHistory.cpp"
"D:\PROJECTS\Sports\Soccer\ManagerOfTheMonth.cpp"
"D:\PROJECTS\Sports\Soccer\News.cpp"
"D:\PROJECTS\Sports\Soccer\OutOfContractPlayer.cpp"
"D:\PROJECTS\Sports\Soccer\Person.cpp"
"D:\PROJECTS\Sports\Soccer\PlayerSearch.cpp"
"D:\PROJECTS\Sports\Soccer\Popular.cpp"
"D:\PROJECTS\Sports\Soccer\Rating.cpp"
"D:\PROJECTS\Sports\Soccer\RecordAttendance.cpp"
"D:\PROJECTS\Sports\Soccer\RefusedDeals.cpp"
"D:\PROJECTS\Sports\Soccer\SkillMoneyValues.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerPlayerPerformance.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerResult.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerSquadTraining.cpp"
"D:\PROJECTS\Sports\Soccer\SoccerTactic.cpp"
"D:\PROJECTS\Sports\Soccer\Stadium.cpp"
"D:\PROJECTS\Sports\Soccer\StringID.cpp"
"D:\PROJECTS\Sports\Soccer\TableData.cpp"
"D:\PROJECTS\Sports\Soccer\TeamOfTheWeek.cpp"
"D:\PROJECTS\Sports\Soccer\TransferNegotiation.cpp"
"D:\PROJECTS\Sports\Soccer\TrophyHistory.cpp"
"D:\PROJECTS\Sports\Soccer\WorldData.cpp"
"D:\PROJECTS\Sports\Soccer\Youth.cpp"
"D:\PROJECTS\system\AppPreferences.cpp"
"D:\PROJECTS\system\BasicDisplay.cpp"
"D:\PROJECTS\system\BinaryResource.cpp"
"D:\PROJECTS\system\Date.cpp"
"D:\PROJECTS\system\DateDisplay.cpp"
"D:\PROJECTS\system\ExtEdit.cpp"
"D:\PROJECTS\system\ExtOffScreenBuffer.cpp"
"D:\PROJECTS\system\ExtPropertySheet.cpp"
"D:\PROJECTS\system\ExtRect.cpp"
"D:\PROJECTS\system\ExtStatic.cpp"
"D:\PROJECTS\system\ExtString.cpp"
"D:\PROJECTS\system\HandangoRegCode.cpp"
"D:\PROJECTS\system\IndexedIntArray.cpp"
"D:\PROJECTS\system\INTED.CPP"
"D:\PROJECTS\system\KeyScrollBar.cpp"
"D:\PROJECTS\system\ListStatic.cpp"
"D:\PROJECTS\system\Loanrepay.cpp"
"D:\PROJECTS\system\LWFormView.cpp"
"D:\PROJECTS\system\MessageDisplay.cpp"
"D:\PROJECTS\system\NonDuplicateStringList.cpp"
"D:\PROJECTS\system\OffScreenBuffer.cpp"
"D:\PROJECTS\system\PNGButton.cpp"
"D:\PROJECTS\system\PNGDrawInfo.cpp"
"D:\PROJECTS\system\Random.cpp"
"D:\PROJECTS\system\RoundMoney.CPP"
"D:\PROJECTS\system\ScrollList.cpp"
"D:\PROJECTS\system\SoundVolume.cpp"
"D:\PROJECTS\system\SplashScreen.cpp"
"D:\PROJECTS\system\storagelistbox.cpp"
"D:\PROJECTS\system\SystemPreferences.cpp"
"D:\PROJECTS\system\VOImage.cpp"
"D:\PROJECTS\system\voregistry.cpp"
"D:\PROJECTS\system\VOString.cpp"
"D:\PROJECTS\system\VScrollDialog.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen02View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen04.cpp"
"D:\PROJECTS\POCKETPCFM\Screen05Dlg.cpp"
"D:\PROJECTS\POCKETPCFM\Screen05View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen06.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen06Availability.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen06Skill.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen08Display.cpp"
"D:\PROJECTS\POCKETPCFM\Screen08View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen09View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen11View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen12.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen13.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen14.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen16.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen17.cpp"
"D:\PROJECTS\POCKETPCFM\Screen18Dlg.cpp"
"D:\PROJECTS\POCKETPCFM\Screen18View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen19Display.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen19View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen20View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen21.cpp"
"D:\PROJECTS\POCKETPCFM\Screen22View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen23.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen24.cpp"
"D:\PROJECTS\POCKETPCFM\Screen26View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen27FormationPage.cpp"
"D:\PROJECTS\POCKETPCFM\Screen27FormationView.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen27SpecialPlayersPage.cpp"
"D:\PROJECTS\POCKETPCFM\Screen27SpecialPlayersView.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen27TacticsPage.cpp"
"D:\PROJECTS\POCKETPCFM\Screen27TacticsView.cpp"
"D:\PROJECTS\POCKETPCFM\Screen28View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen30.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen32.cpp"
"D:\PROJECTS\POCKETPCFM\Screen33View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen35.cpp"
"D:\PROJECTS\POCKETPCFM\Screen36View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen39View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen41View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen42.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen46View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen47Dlg.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen48View.cpp"
"D:\PROJECTS\POCKETPCFM\Screen49Dlg.cpp"
"D:\PROJECTS\POCKETPCFM\Screen50View.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen59.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen60.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen61.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen65.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen65Commentary.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen65Events.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen65LineUps.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen65PropertyPage.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen65Skill.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen65Substitutions.cpp"
"D:\PROJECTS\POCKETPCFM\Screen90.cpp"
"D:\PROJECTS\POCKETPCFM\Screen91.cpp"
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\Screen92.cpp"
"D:\PROJECTS\POCKETPCFM\Screen97.cpp"
"D:\PROJECTS\POCKETPCFM\Screen98.cpp"
"D:\PROJECTS\POCKETPCFM\Screen99.cpp"
]
Creating command line "clsh.exe @e:\temp\RSPC995.tmp" 
Creating temporary file "e:\temp\RSPC9C5.tmp" with contents
[
/nologo /W3 /Zi /Od /I "..\..\..\..\PocketPCFM" /D "DEBUG" /D "SHx" /D "SH3" /D "_SH3_" /D UNDER_CE=400 /D _WIN32_WCE=400 /D "WCE_PLATFORM_STANDARDSDK" /D "UNICODE" /D "_UNICODE" /D "_AFXDLL" /Fp"e:\FootballDirector\PocketPC\PocketPCFM.pch" /Yu"stdafx.h" /Fo"e:\FootballDirector\PocketPC\\" /Fd"e:\FootballDirector\PocketPC\\" /MC /c 
"D:\PROJECTS\Applications\FootballDirector\Windows\Dialogs\screen54.cpp"
]
Creating command line "clsh.exe @e:\temp\RSPC9C5.tmp" 
Creating temporary file "e:\temp\RSPC9C6.tmp" with contents
[
/nologo /W3 /Zi /Od /D "DEBUG" /D "SHx" /D "SH3" /D "_SH3_" /D UNDER_CE=400 /D _WIN32_WCE=400 /D "WCE_PLATFORM_STANDARDSDK" /D "UNICODE" /D "_UNICODE" /D "_AFXDLL" /Fp"e:\FootballDirector\PocketPC\PocketPCFM.pch" /Yc"stdafx.h" /Fo"e:\FootballDirector\PocketPC\\" /Fd"e:\FootballDirector\PocketPC\\" /MC /c 
"D:\PROJECTS\POCKETPCFM\StdAfx.cpp"
]
Creating command line "clsh.exe @e:\temp\RSPC9C6.tmp" 
Creating temporary file "e:\temp\RSPCA06.tmp" with contents
[
/nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"wWinMainCRTStartup" /incremental:yes /pdb:"e:\FootballDirector\PocketPC\Football Director.pdb" /debug /out:"SH3Rel/Football Director.exe" /subsystem:windowsce,4.00 /MACHINE:SH3 
e:\FootballDirector\PocketPC\ClubListBox.obj
e:\FootballDirector\PocketPC\DivisionListBox.obj
e:\FootballDirector\PocketPC\FootballDirectorDoc.obj
e:\FootballDirector\PocketPC\FootballDirectorView.obj
e:\FootballDirector\PocketPC\MainFrm.obj
e:\FootballDirector\PocketPC\MainMenu.obj
e:\FootballDirector\PocketPC\PopupPlayerMenu.obj
e:\FootballDirector\PocketPC\SoundManager.obj
e:\FootballDirector\PocketPC\StdAfx.obj
e:\FootballDirector\PocketPC\TheApp.obj
e:\FootballDirector\PocketPC\MatchActionItem.obj
e:\FootballDirector\PocketPC\MatchCommentary.obj
e:\FootballDirector\PocketPC\MatchEvent.obj
e:\FootballDirector\PocketPC\MatchEventsStats.obj
e:\FootballDirector\PocketPC\MatchHandler.obj
e:\FootballDirector\PocketPC\MatchInfo.obj
e:\FootballDirector\PocketPC\MatchPlay.obj
e:\FootballDirector\PocketPC\MatchSubs.obj
e:\FootballDirector\PocketPC\MatchTeamSkills.obj
e:\FootballDirector\PocketPC\MatchTime.obj
e:\FootballDirector\PocketPC\MatchVars.obj
e:\FootballDirector\PocketPC\MatchVarsData.obj
e:\FootballDirector\PocketPC\PenaltyShootOut.obj
e:\FootballDirector\PocketPC\SoccerBallPitchLocation.obj
e:\FootballDirector\PocketPC\SoccerMatchPlayer.obj
e:\FootballDirector\PocketPC\Chairman.obj
e:\FootballDirector\PocketPC\Club.obj
e:\FootballDirector\PocketPC\ClubFriendlies.obj
e:\FootballDirector\PocketPC\ClubHistory.obj
e:\FootballDirector\PocketPC\ClubList.obj
e:\FootballDirector\PocketPC\ClubMatchDetails.obj
e:\FootballDirector\PocketPC\ClubSeasonStats.obj
e:\FootballDirector\PocketPC\ClubTransferOffer.obj
e:\FootballDirector\PocketPC\FansReaction.obj
e:\FootballDirector\PocketPC\SeasonLeaguePosition.obj
e:\FootballDirector\PocketPC\Injury.obj
e:\FootballDirector\PocketPC\InjuryType.obj
e:\FootballDirector\PocketPC\Player.obj
e:\FootballDirector\PocketPC\PlayerContract.obj
e:\FootballDirector\PocketPC\PlayerDiscipline.obj
e:\FootballDirector\PocketPC\PlayerLoan.obj
e:\FootballDirector\PocketPC\PlayerRating.obj
e:\FootballDirector\PocketPC\PlayerSquad.obj
e:\FootballDirector\PocketPC\PlayerTransferStatus.obj
e:\FootballDirector\PocketPC\SoccerPlayer.obj
e:\FootballDirector\PocketPC\SoccerPlayerCareer.obj
e:\FootballDirector\PocketPC\SoccerPlayerCareerPath.obj
e:\FootballDirector\PocketPC\BaseCompetition.obj
e:\FootballDirector\PocketPC\CharityShield.obj
e:\FootballDirector\PocketPC\Competition.obj
e:\FootballDirector\PocketPC\Cup.obj
e:\FootballDirector\PocketPC\CupDisplayEvent.obj
e:\FootballDirector\PocketPC\CupRound.obj
e:\FootballDirector\PocketPC\CupTiedPlayer.obj
e:\FootballDirector\PocketPC\Division.obj
e:\FootballDirector\PocketPC\Playoff.obj
e:\FootballDirector\PocketPC\Accounts.obj
e:\FootballDirector\PocketPC\Aggression.obj
e:\FootballDirector\PocketPC\AvailableSubstitutes.obj
e:\FootballDirector\PocketPC\BasicEmployee.obj
e:\FootballDirector\PocketPC\ContractClause.obj
e:\FootballDirector\PocketPC\Country.obj
e:\FootballDirector\PocketPC\CupWinnersInfo.obj
e:\FootballDirector\PocketPC\Currency.obj
e:\FootballDirector\PocketPC\CurrentForm.obj
e:\FootballDirector\PocketPC\DivisionStrength.obj
e:\FootballDirector\PocketPC\Employee.obj
e:\FootballDirector\PocketPC\Federation.obj
e:\FootballDirector\PocketPC\FinancialLoan.obj
e:\FootballDirector\PocketPC\Fixture.obj
e:\FootballDirector\PocketPC\FixtureController.obj
e:\FootballDirector\PocketPC\HumanManager.obj
e:\FootballDirector\PocketPC\LeadingDisciplinaryPoints.obj
e:\FootballDirector\PocketPC\LeadingGoalscorer.obj
e:\FootballDirector\PocketPC\Manager.obj
e:\FootballDirector\PocketPC\ManagerHistory.obj
e:\FootballDirector\PocketPC\ManagerOfTheMonth.obj
e:\FootballDirector\PocketPC\News.obj
e:\FootballDirector\PocketPC\OutOfContractPlayer.obj
e:\FootballDirector\PocketPC\Person.obj
e:\FootballDirector\PocketPC\PlayerSearch.obj
e:\FootballDirector\PocketPC\Popular.obj
e:\FootballDirector\PocketPC\Rating.obj
e:\FootballDirector\PocketPC\RecordAttendance.obj
e:\FootballDirector\PocketPC\RefusedDeals.obj
e:\FootballDirector\PocketPC\SkillMoneyValues.obj
e:\FootballDirector\PocketPC\SoccerPlayerPerformance.obj
e:\FootballDirector\PocketPC\SoccerResult.obj
e:\FootballDirector\PocketPC\SoccerSquadTraining.obj
e:\FootballDirector\PocketPC\SoccerTactic.obj
e:\FootballDirector\PocketPC\Stadium.obj
e:\FootballDirector\PocketPC\StringID.obj
e:\FootballDirector\PocketPC\TableData.obj
e:\FootballDirector\PocketPC\TeamOfTheWeek.obj
e:\FootballDirector\PocketPC\TransferNegotiation.obj
e:\FootballDirector\PocketPC\TrophyHistory.obj
e:\FootballDirector\PocketPC\WorldData.obj
e:\FootballDirector\PocketPC\Youth.obj
e:\FootballDirector\PocketPC\AppPreferences.obj
e:\FootballDirector\PocketPC\BasicDisplay.obj
e:\FootballDirector\PocketPC\BinaryResource.obj
e:\FootballDirector\PocketPC\Date.obj
e:\FootballDirector\PocketPC\DateDisplay.obj
e:\FootballDirector\PocketPC\ExtEdit.obj
e:\FootballDirector\PocketPC\ExtOffScreenBuffer.obj
e:\FootballDirector\PocketPC\ExtPropertySheet.obj
e:\FootballDirector\PocketPC\ExtRect.obj
e:\FootballDirector\PocketPC\ExtStatic.obj
e:\FootballDirector\PocketPC\ExtString.obj
e:\FootballDirector\PocketPC\HandangoRegCode.obj
e:\FootballDirector\PocketPC\IndexedIntArray.obj
e:\FootballDirector\PocketPC\INTED.OBJ
e:\FootballDirector\PocketPC\KeyScrollBar.obj
e:\FootballDirector\PocketPC\ListStatic.obj
e:\FootballDirector\PocketPC\Loanrepay.obj
e:\FootballDirector\PocketPC\LWFormView.obj
e:\FootballDirector\PocketPC\MessageDisplay.obj
e:\FootballDirector\PocketPC\NonDuplicateStringList.obj
e:\FootballDirector\PocketPC\OffScreenBuffer.obj
e:\FootballDirector\PocketPC\PNGButton.obj
e:\FootballDirector\PocketPC\PNGDrawInfo.obj
e:\FootballDirector\PocketPC\Random.obj
e:\FootballDirector\PocketPC\RoundMoney.obj
e:\FootballDirector\PocketPC\ScrollList.obj
e:\FootballDirector\PocketPC\SoundVolume.obj
e:\FootballDirector\PocketPC\SplashScreen.obj
e:\FootballDirector\PocketPC\storagelistbox.obj
e:\FootballDirector\PocketPC\SystemPreferences.obj
e:\FootballDirector\PocketPC\VOImage.obj
e:\FootballDirector\PocketPC\voregistry.obj
e:\FootballDirector\PocketPC\VOString.obj
e:\FootballDirector\PocketPC\VScrollDialog.obj
e:\FootballDirector\PocketPC\Screen02View.obj
e:\FootballDirector\PocketPC\Screen04.obj
e:\FootballDirector\PocketPC\Screen05Dlg.obj
e:\FootballDirector\PocketPC\Screen05View.obj
e:\FootballDirector\PocketPC\Screen06.obj
e:\FootballDirector\PocketPC\Screen06Availability.obj
e:\FootballDirector\PocketPC\Screen06Skill.obj
e:\FootballDirector\PocketPC\Screen08Display.obj
e:\FootballDirector\PocketPC\Screen08View.obj
e:\FootballDirector\PocketPC\Screen09View.obj
e:\FootballDirector\PocketPC\Screen11View.obj
e:\FootballDirector\PocketPC\Screen12.obj
e:\FootballDirector\PocketPC\Screen13.obj
e:\FootballDirector\PocketPC\Screen14.obj
e:\FootballDirector\PocketPC\Screen16.obj
e:\FootballDirector\PocketPC\Screen17.obj
e:\FootballDirector\PocketPC\Screen18Dlg.obj
e:\FootballDirector\PocketPC\Screen18View.obj
e:\FootballDirector\PocketPC\Screen19Display.obj
e:\FootballDirector\PocketPC\Screen19View.obj
e:\FootballDirector\PocketPC\Screen20View.obj
e:\FootballDirector\PocketPC\Screen21.obj
e:\FootballDirector\PocketPC\Screen22View.obj
e:\FootballDirector\PocketPC\Screen23.obj
e:\FootballDirector\PocketPC\Screen24.obj
e:\FootballDirector\PocketPC\Screen26View.obj
e:\FootballDirector\PocketPC\Screen27FormationPage.obj
e:\FootballDirector\PocketPC\Screen27FormationView.obj
e:\FootballDirector\PocketPC\Screen27SpecialPlayersPage.obj
e:\FootballDirector\PocketPC\Screen27SpecialPlayersView.obj
e:\FootballDirector\PocketPC\Screen27TacticsPage.obj
e:\FootballDirector\PocketPC\Screen27TacticsView.obj
e:\FootballDirector\PocketPC\Screen28View.obj
e:\FootballDirector\PocketPC\Screen30.obj
e:\FootballDirector\PocketPC\Screen32.obj
e:\FootballDirector\PocketPC\Screen33View.obj
e:\FootballDirector\PocketPC\Screen35.obj
e:\FootballDirector\PocketPC\Screen36View.obj
e:\FootballDirector\PocketPC\Screen39View.obj
e:\FootballDirector\PocketPC\Screen41View.obj
e:\FootballDirector\PocketPC\Screen42.obj
e:\FootballDirector\PocketPC\Screen46View.obj
e:\FootballDirector\PocketPC\Screen47Dlg.obj
e:\FootballDirector\PocketPC\Screen48View.obj
e:\FootballDirector\PocketPC\Screen49Dlg.obj
e:\FootballDirector\PocketPC\Screen50View.obj
e:\FootballDirector\PocketPC\screen54.obj
e:\FootballDirector\PocketPC\Screen59.obj
e:\FootballDirector\PocketPC\Screen60.obj
e:\FootballDirector\PocketPC\Screen61.obj
e:\FootballDirector\PocketPC\Screen65.obj
e:\FootballDirector\PocketPC\Screen65Commentary.obj
e:\FootballDirector\PocketPC\Screen65Events.obj
e:\FootballDirector\PocketPC\Screen65LineUps.obj
e:\FootballDirector\PocketPC\Screen65PropertyPage.obj
e:\FootballDirector\PocketPC\Screen65Skill.obj
e:\FootballDirector\PocketPC\Screen65Substitutions.obj
e:\FootballDirector\PocketPC\Screen90.obj
e:\FootballDirector\PocketPC\Screen91.obj
e:\FootballDirector\PocketPC\Screen92.obj
e:\FootballDirector\PocketPC\Screen97.obj
e:\FootballDirector\PocketPC\Screen98.obj
e:\FootballDirector\PocketPC\Screen99.obj
e:\FootballDirector\PocketPC\PocketPCFM.res
]
Creating command line "link.exe @e:\temp\RSPCA06.tmp"
<h3>Output Window</h3>
Compiling resources...
Compiling...
StdAfx.cpp
d:\projects\system\helpinfo.h(14) : error C2011: 'tagHELPINFO' : 'struct' type redefinition
Error executing clsh.exe.



<h3>Results</h3>
Football Director.exe - 1 error(s), 0 warning(s)
</pre>
</body>
</html>
