

 /*

	File:- MatchEvent.h

    Match Event class

	Information about the match event, is stored within CFixture

	Football Director

	(c) Rw Software 1994 - 2008

  ---------------------------------------------------------------------------------------
*/

#ifndef __MATCHEVENT_H__
#define __MATCHEVENT_H__

enum eMatchEvent
{
	NOEVENT,
	HOMEGOAL, AWAYGOAL,                                 // 3
	HOMEBOOKING, AWAYBOOKING,                           // 5
	HOMESENDINGOFF, AWAYSENDINGOFF,                     // 7
	HOMEOWNGOAL, AWAYOWNGOAL,                           // 9
	HOMEPENALTYGOAL, AWAYPENALTYGOAL,                   // 11
	HOMEOFFSIDEATTEMPT, AWAYOFFSIDEATTEMPT,             // 13
	HOMEFOULPLAYERATTEMPT, AWAYFOULPLAYERATTEMPT,       // 15
	HOMEINJUREPLAYERATTEMPT, AWAYINJUREPLAYERATTEMPT,   // 17
	HOMESHOTATTEMPT, AWAYSHOTATTEMPT,                   // 19
	HOMEMISSATTEMPT, AWAYMISSATTEMPT,                   // 21
	HOMEFREEKICKATTEMPT, AWAYFREEKICKATTEMPT,           // 23
	HOMECORNERATTEMPT, AWAYCORNERATTEMPT,               // 25
	HOMESUBATTEMPT, AWAYSUBATTEMPT,                     // 27
	// Sub events
	HOMEFREEKICKINDIRECT, AWAYFREEKICKINDIRECT,
	HOMEFREEKICKDEFLECTED, AWAYFREEKICKDEFLECTED,
	HOMEFREEKICKCLEARED, AWAYFREEKICKCLEARED,
	HOMEFREEKICKOFFTARGET, AWAYFREEKICKOFFTARGET,
	HOMEFREEKICKONTARGET, AWAYFREEKICKONTARGET,
	HOMEFREEKICKGOAL, AWAYFREEKICKGOAL,					// 39

	HOMEFREEKICKINDIRECTYELLOWGOALKEEPER, AWAYFREEKICKINDIRECTYELLOWGOALKEEPER,			// 41
	HOMEFREEKICKDEFLECTEDYELLOWGOALKEEPER, AWAYFREEKICKDEFLECTEDYELLOWGOALKEEPER,
	HOMEFREEKICKCLEAREDYELLOWGOALKEEPER, AWAYFREEKICKCLEAREDYELLOWGOALKEEPER,
	HOMEFREEKICKOFFTARGETYELLOWGOALKEEPER, AWAYFREEKICKOFFTARGETYELLOWGOALKEEPER,
	HOMEFREEKICKONTARGETYELLOWGOALKEEPER, AWAYFREEKICKONTARGETYELLOWGOALKEEPER,
	HOMEFREEKICKGOALYELLOWGOALKEEPER, AWAYFREEKICKGOALYELLOWGOALKEEPER,					// 51

	HOMEFREEKICKINDIRECTYELLOWOUTFIELDPLAYER, AWAYFREEKICKINDIRECTYELLOWOUTFIELDPLAYER,
	HOMEFREEKICKDEFLECTEDYELLOWOUTFIELDPLAYER, AWAYFREEKICKDEFLECTEDYELLOWOUTFIELDPLAYER,
	HOMEFREEKICKCLEAREDYELLOWOUTFIELDPLAYER, AWAYFREEKICKCLEAREDYELLOWOUTFIELDPLAYER,
	HOMEFREEKICKOFFTARGETYELLOWOUTFIELDPLAYER, AWAYFREEKICKOFFTARGETYELLOWOUTFIELDPLAYER,
	HOMEFREEKICKONTARGETYELLOWOUTFIELDPLAYER, AWAYFREEKICKONTARGETYELLOWOUTFIELDPLAYER,
	HOMEFREEKICKGOALYELLOWOUTFIELDPLAYER, AWAYFREEKICKGOALYELLOWOUTFIELDPLAYER,			// 63

	HOMEFREEKICKINDIRECTREDGOALKEEPER, AWAYFREEKICKINDIRECTREDGOALKEEPER,
	HOMEFREEKICKDEFLECTEDREDGOALKEEPER, AWAYFREEKICKDEFLECTEDREDGOALKEEPER,
	HOMEFREEKICKCLEAREDREDGOALKEEPER, AWAYFREEKICKCLEAREDREDGOALKEEPER,
	HOMEFREEKICKOFFTARGETREDGOALKEEPER, AWAYFREEKICKOFFTARGETREDGOALKEEPER,
	HOMEFREEKICKONTARGETREDGOALKEEPER, AWAYFREEKICKONTARGETREDGOALKEEPER,
	HOMEFREEKICKGOALREDGOALKEEPER, AWAYFREEKICKGOALREDGOALKEEPER,						// 75

	HOMEFREEKICKINDIRECTREDOUTFIELDPLAYER, AWAYFREEKICKINDIRECTREDOUTFIELDPLAYER,
	HOMEFREEKICKDEFLECTEDREDOUTFIELDPLAYER, AWAYFREEKICKDEFLECTEDREDOUTFIELDPLAYER,
	HOMEFREEKICKCLEAREDREDOUTFIELDPLAYER, AWAYFREEKICKCLEAREDREDOUTFIELDPLAYER,
	HOMEFREEKICKOFFTARGETREDOUTFIELDPLAYER, AWAYFREEKICKOFFTARGETREDOUTFIELDPLAYER,
	HOMEFREEKICKONTARGETREDOUTFIELDPLAYER, AWAYFREEKICKONTARGETREDOUTFIELDPLAYER,
	HOMEFREEKICKGOALREDOUTFIELDPLAYER, AWAYFREEKICKGOALREDOUTFIELDPLAYER,				// 87

	HOMETOPCORNERDEFLECTED, AWAYTOPCORNERDEFLECTED,
	HOMEBOTTOMCORNERDEFLECTED, AWAYBOTTOMCORNERDEFLECTED,								// 91
	HOMETOPCORNERCLEARED, AWAYTOPCORNERCLEARED,
	HOMEBOTTOMCORNERCLEARED, AWAYBOTTOMCORNERCLEARED,
	HOMETOPCORNEROFFTARGET, AWAYTOPCORNEROFFTARGET,
	HOMEBOTTOMCORNEROFFTARGET, AWAYBOTTOMCORNEROFFTARGET,								// 99
	HOMETOPCORNERONTARGET, AWAYTOPCORNERONTARGET,
	HOMEBOTTOMCORNERONTARGET, AWAYBOTTOMCORNERONTARGET,									// 103
	HOMETOPCORNERGOALSHOT, AWAYTOPCORNERGOALSHOT,
	HOMETOPCORNERGOALHEADER, AWAYTOPCORNERGOALHEADER,									// 107
	HOMEBOTTOMCORNERGOALSHOT, AWAYBOTTOMCORNERGOALSHOT,
	HOMEBOTTOMCORNERGOALHEADER, AWAYBOTTOMCORNERGOALHEADER,								// 109
	// Player walking off, sub walking on
	HOMEGOALKEEPERSUBSTITUTED, AWAYGOALKEEPERSUBSTITUTED,								// 111
	HOMEDEFENDERSUBSTITUTED, AWAYDEFENDERSUBSTITUTED,									// 113
	HOMEMIDFIELDERSUBSTITUTED, AWAYMIDFIELDERSUBSTITUTED,								// 115
	HOMEATTACKERSUBSTITUTED, AWAYATTACKERSUBSTITUTED,									// 117
	HOMEGOALSHOT, AWAYGOALSHOT,															// 119
	HOMEGOALHEADER, AWAYGOALHEADER,														// 121
	// Penalties
	HOMEPENALTYSAVED, AWAYPENALTYSAVED,
	HOMEPENALTYMISS, AWAYPENALTYMISS,
	HOMEPENALTYSAVEDYELLOWGOALKEEPER, AWAYPENALTYSAVEDYELLOWGOALKEEPER,
	HOMEPENALTYMISSYELLOWGOALKEEPER, AWAYPENALTYMISSYELLOWGOALKEEPER,
	HOMEPENALTYGOALYELLOWGOALKEEPER, AWAYPENALTYGOALYELLOWGOALKEEPER,
	HOMEPENALTYSAVEDREDGOALKEEPER, AWAYPENALTYSAVEDREDGOALKEEPER,						// 133
	HOMEPENALTYMISSREDGOALKEEPER, AWAYPENALTYMISSREDGOALKEEPER,
	HOMEPENALTYGOALREDGOALKEEPER, AWAYPENALTYGOALREDGOALKEEPER,
	HOMEPENALTYSAVEDYELLOWOUTFIELDPLAYER, AWAYPENALTYSAVEDYELLOWOUTFIELDPLAYER,
	HOMEPENALTYMISSYELLOWOUTFIELDPLAYER, AWAYPENALTYMISSYELLOWOUTFIELDPLAYER,
	HOMEPENALTYGOALYELLOWOUTFIELDPLAYER, AWAYPENALTYGOALYELLOWOUTFIELDPLAYER,
	HOMEPENALTYSAVEDREDOUTFIELDPLAYER, AWAYPENALTYSAVEDREDOUTFIELDPLAYER,
	HOMEPENALTYMISSREDOUTFIELDPLAYER, AWAYPENALTYMISSREDOUTFIELDPLAYER,
	HOMEPENALTYGOALREDOUTFIELDPLAYER, AWAYPENALTYGOALREDOUTFIELDPLAYER,					// 149

	HOMESHOTATTEMPTSHOT, AWAYSHOTATTEMPTSHOT,
	HOMESHOTATTEMPTHEADER, AWAYSHOTATTEMPTHEADER,
	HOMEMISSATTEMPTSHOT, AWAYMISSATTEMPTSHOT,
	HOMEMISSATTEMPTHEADER, AWAYMISSATTEMPTHEADER,
	HOMEDISALLOWEDSHOT, AWAYDISALLOWEDSHOT,
	HOMEDISALLOWEDHEADER, AWAYDISALLOWEDHEADER,											// 161
	// Penalty shoot out
	HOMEPENALTYSHOOTOUTGOAL, AWAYPENALTYSHOOTOUTGOAL,
	HOMEPENALTYSHOOTOUTSAVED, AWAYPENALTYSHOOTOUTSAVED,
	HOMEPENALTYSHOOTOUTMISS, AWAYPENALTYSHOOTOUTMISS,									// 167
	// Injuries
	HOMEGOALKEEPERHOBBLE, HOMEGOALKEEPERCARRIEDOFF,										// 169
	HOMEOUTFIELDPLAYERHOBBLE, HOMEOUTFIELDPLAYERCARRIEDOFF,
	AWAYGOALKEEPERHOBBLE, AWAYGOALKEEPERCARRIEDOFF,
	AWAYOUTFIELDPLAYERHOBBLE, AWAYOUTFIELDPLAYERCARRIEDOFF,
	HOMEGOALKEEPERINJURYOK, HOMEOUTFIELDPLAYERINJURYOK,
	AWAYGOALKEEPERINJURYOK, AWAYOUTFIELDPLAYERINJURYOK,									// 179
	// Injured, take off and show sub coming on
	HOMEGOALKEEPERHOBBLESUBON, HOMEGOALKEEPERCARRIEDOFFSUBON,							// 181
	HOMEOUTFIELDPLAYERHOBBLESUBON, HOMEOUTFIELDPLAYERCARRIEDOFFSUBON,
	AWAYGOALKEEPERHOBBLESUBON, AWAYGOALKEEPERCARRIEDOFFSUBON,
	AWAYOUTFIELDPLAYERHOBBLESUBON, AWAYOUTFIELDPLAYERCARRIEDOFFSUBON,
	// Sub walking on
	HOMEGOALKEEPERSUBON, AWAYGOALKEEPERSUBON,
	HOMEDEFENDERSUBON, AWAYDEFENDERSUBON,
	HOMEMIDFIELDERSUBON, AWAYMIDFIELDERSUBON,
	HOMEATTACKERSUBON, AWAYATTACKERSUBON,
	// Injured, take off and don't show sub coming on(all subs used)
	HOMEGOALKEEPERHOBBLENOSUBON, HOMEGOALKEEPERCARRIEDOFFNOSUBON,
	HOMEOUTFIELDPLAYERHOBBLENOSUBON, HOMEOUTFIELDPLAYERCARRIEDOFFNOSUBON,
	AWAYGOALKEEPERHOBBLENOSUBON, AWAYGOALKEEPERCARRIEDOFFNOSUBON,
	AWAYOUTFIELDPLAYERHOBBLENOSUBON, AWAYOUTFIELDPLAYERCARRIEDOFFNOSUBON
};


class CMatchEvent 
{
    // Variables
private:
    byte					m_Time;
    byte					m_Type;
    CPersonName             m_PlayerName;

public:
	// Constructors
    CMatchEvent() {};
    CMatchEvent(const byte _Time, const byte _Type, const CPersonName _Name);

    // Methods
	void					DoResetVariables();
	eMatchEvent				GetEventType() const;								
	CString					GetText();								
	CString					GetEventDiscTimeStr();
	CString					GetEventGoalTimeStr();
	byte					GetTime() const;
	bool					IsBookingEvent();
	bool					IsDiscEvent();
	bool					IsGoalEvent();
	bool					IsHomeTeamEvent();
	bool					IsOwnGoal();
	bool					IsPenalty();
	bool					IsPenaltyShootOutEvent();
	bool					IsSendingOffEvent();
};
///////////////////////////////////////////////////////////////////////////////////////////////


class CMatchEventList : public CPointerArray<CMatchEvent>
{
public:
    CMatchEventList() {};          // Constructor

	// IO Methods
	void					Write(CDataFile* _pDataFile);
	void					Read(CDataFile* _pDataFile);

    // Methods
	uint					AwayScore(const uint _Time);
    int                     AwayNumberPlayersBooked();
    int                     AwayNumberPlayersSentOff();
	CString					AwayPlayerScoredStr(const ushort _EventNumber);
	CString					AwayPlayerBookedStr(const ushort _EventNumber);
	CString					AwayPlayerSentOffStr(const ushort _EventNumber);
	int						DoCalculateGoalDifference();
	int						DoCountEvents(eMatchEvent _EventType);
	int						DoCountInGameEvents();
    CString		            GetLastEventStr();
	CString					GetEventStr(const ushort _EventNumber);
    CString		            GetLastEventTimeStr();
	bool					HasGoalBeenScored(const uint _Time);
    int                     HomeNumberPlayersBooked();
	uint					HomeScore(const uint _Time);
	uint					HalfTimeAwayGoals();
	uint					HalfTimeHomeGoals();
    int                     HomeNumberPlayersSentOff();
	CString					HomePlayerScoredStr(const ushort _EventNumber);
	CString					HomePlayerBookedStr(const ushort _EventNumber);
	CString					HomePlayerSentOffStr(const ushort _EventNumber);
    int                     NumberHomeOwnGoals();
    int                     NumberAwayOwnGoals();
    int                     NumberHomePenaltyGoals();
    int                     NumberAwayPenaltyGoals();
	int						NumberAwayPenaltyShootOutGoals();
	int						NumberHomePenaltyShootOutGoals();
	CMatchEvent*			GetFreeMatchEvent();
	eWhichTeam				PenaltyShootoutWinner();
	CString					PenaltyShootoutWinnerStr(const CString _HomeClubName, const CString _AwayClubName);
    void                    SortByType();
    void                    SortByTime();
	bool					WasPenaltyShootOut();
	bool					IsAwayEvent(const ushort _EventNumber);
	bool					IsHomeEvent(const ushort _EventNumber);
};
#endif
