#include "PlayerSelector.h"
#include "DivisionSelector.h"

#include "BitmapDialog.h"
#include "DivisionSelectorBitmapDialog.h"
#include "InMatchActionBitmapDialog.h"
#include "Screen27FormationDlg.h"
#include "Screen27SpecialPlayersDlg.h"
#include "Screen27TacticsData.h"
#include "Screen27TacticsDlg.h"
#include "Screen64Dlg.h"